-- VAMOS A CREAR DOS COLUMNAS PARA SEPARA NOMBRES Y APELLIDOS
ALTER TABLE users
ADD COLUMN first_name VARCHAR(50),
ADD COLUMN last_name VARCHAR(50);

-- AHORA VAMOS A RELLENAR ESAS DOS COLUMNAS USANDO SUBSTRING Y POSITION
UPDATE users
SET 
    first_name = SUBSTRING (name, 0, (POSITION ( ' ' in name)))
    last_name = SUBSTRING(name, (POSITION ( ' ' in name) + 1 ), LENGTH(name))

SELECT * FROM users;