-- VER TODOS LOS REGISTROS DE UNA TABLA
SELECT * FROM productos;

-- CONSULTAR COLUMNAS ESPECÍFICAS
SELECT nombre, precio FROM productos;

-- FILTRAR REGISTROS CON WHERE
SELECT * FROM productos
WHERE precio > 100.00;

-- ORDENAR RESULTADOS CON ORDER BY
SELECT * FROM productos
ORDER BY precio DESC;

-- lIMITAR EL NÚMERO DE REGISTROS DEVUELTOS
SELECT * FROM productos
LIMIT 5;

