-- VAMOS A APRENDER A MANEJAR STRINGS EN SQL SIN AFECTAR LAS TABLAS

-- FUNCION UPPER: CONVIERTE UNA CADENA DE TEXTO A MAYUSCULAS
SELECT UPPER('hola que tal');

-- HACER QUE UNA COLUMNA DE TEXTO ESTE EN MAYUSCULAS
SELECT
    UPPER(nombre_columna) AS nombre_columna
FROM
    Nombre_tabla


-- FUNCION LOWER: CONVIERTE UNA CADENA DE TEXTO A MINUSCULAS
SELECT LOWER('HOLA QUE TAL');

-- HACER QUE UNA COLUMNA DE TEXTO ESTE EN MINUSCULAS
SELECT
    LOWER(nombre_columna) AS nombre_columna
FROM
    Nombre_tabla;


-- FUNCION LENGTH: DEVUELVE LA CANTIDAD DE CARACTERES DE UNA CADENA DE TEXTO
SELECT LENGTH('Hola que tal');

-- OBTENER LA CANTIDAD DE CARACTERES DE UNA COLUMNA DE TEXTO
SELECT
    LENGTH(nombre_columna) AS cantidad_caracteres
FROM
    Nombre_tabla;

