-- LA FUNCION SUBSTRING EN SQL NOS SIRVE PARA CORTAR CADENAS DE TEXTO.
-- LA SINTAXIS ES LA SIGUIENTE:

SUBSTRING(cadena_de_texto FROM posicion_inicial FOR numero_de_caracteres);

SUBSTRING(nombre_columna, posicion_inicial, posicion_final);

-- EJEMPLO:
SELECT 
    SUBSTRING(name, 0, 5) AS texto_cortado;
FROM 
    users;

-- EJMPLO:
SELECT
	name,
    -- CORTAMOS DEL CARACTER 0 HASTA EL 5
	SUBSTRING(name, 0, 5),
    --BUSCAMOS EN QUE POSICION ESTA LA LETRA E EN LOS REGISTROS DE LA COLUMNA LLAMADA name
	POSITION ( 'E' in name)
FROM
	users;

-- EJEMPLO:
SELECT
	name,
    -- CORTAMOS DESDE EL CARACTER 0 HASTA LA POSICION DONDE SE ENCUENTRA EL ESPACIO EN BLANCO
	SUBSTRING(name, 0, (POSITION ( ' ' in name))),
    --BUSCAMOS EN QUE POSICION ESTA EL ESPACIO EN BLANCO EN LOS REGISTROS DE LA COLUMNA LLAMADA name
	POSITION ( ' ' in name)
FROM
	users;
	
	
SELECT
	name,
    -- CORTAMOS DESDE EL CARACTER 0 HASTA LA POSICION DONDE SE ENCUENTRA EL ESPACIO EN BLANCO.
	-- ESTE SERA EL PRIMER NOMBRE.
    SUBSTRING (name, 0, (POSITION ( ' ' in name))) as first_name,
	
    -- CORTAMOS DESDE LA POSICION DEL ESPACIO EN BLANCO + 1 HASTA EL FINAL DE LA CADENA.
    -- LE SUMAMOS 1 PARA NO INCLUIR EL ESPACIO EN BLANCO.
    -- ESTE SERA EL APELLIDO.    
    SUBSTRING(name, (POSITION ( ' ' in name) + 1 ), LENGTH(name)) as last_name
FROM
	users;
	
SELECT
    name,
    -- CORTAMOS DESDE LA POSICION DEL ESPACIO EN BLANCO HASTA EL FINAL DE LA CADENA.
    -- USAMOS TRIM PARA CORTAR EL ESPACIO EN BLANCO INICIAL Y SI HAY UN ESPACIO FINAL TAMBIEN.
    -- ESTE SERA EL APELLIDO.    
    TRIM(SUBSTRING(name, (POSITION ( ' ' in name)), LENGTH(name))) as last_name