-- ELIMINAR REGISTROS DE UNA TABLA
DELETE FROM usuarios
WHERE id = 2;

-- ELIMINAR TODOS LOS REGISTROS DE UNA TABLA
TRUNCATE TABLE usuarios;

-- ELIMINAR REGISTROS DE UNA COLUMNA
UPDATE tabla
SET nombre_columna = NULL

